version: '2'
services:
  web:
    container_name: jekyll
    image: jekyll/jekyll
    entrypoint: /srv/jekyll/entrypoint.sh
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    command: [ "bundle", "exec",  "jekyll", "serve", "--host=0.0.0.0" ]
